# Generated by Django 4.0.4 on 2022-04-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=15)),
                ('rating', models.FloatField()),
                ('poster', models.ImageField(upload_to=None)),
                ('director', models.CharField(max_length=50)),
                ('plot', models.TextField()),
                ('imdb', models.IntegerField()),
                ('tomatometer', models.IntegerField()),
                ('audience_score', models.IntegerField()),
                ('meta_score', models.IntegerField()),
                ('Release_date', models.DateField()),
                ('Country_of_Origin', models.CharField(max_length=50)),
                ('Languages_Spoken', models.CharField(max_length=50)),
                ('Runtime', models.IntegerField()),
                ('Sound_Mix', models.CharField(max_length=50)),
                ('Color', models.CharField(max_length=50)),
                ('Aspect_Ratio', models.CharField(max_length=50)),
            ],
        ),
    ]
