# Generated by Django 4.0.4 on 2022-05-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='car_1',
            field=models.ImageField(null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='movie',
            name='car_2',
            field=models.ImageField(null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='movie',
            name='car_3',
            field=models.ImageField(null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='movie',
            name='car_4',
            field=models.ImageField(null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='movie',
            name='car_5',
            field=models.ImageField(null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='movie',
            name='gemres',
            field=models.TextField(null=True),
        ),
    ]
