# Generated by Django 4.0.4 on 2022-05-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_movie_car_1_movie_car_2_movie_car_3_movie_car_4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='car_1',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='car_2',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='car_3',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='car_4',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='car_5',
        ),
    ]
