# Generated by Django 4.0.4 on 2022-05-03 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_movie_car_1_remove_movie_car_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='poster',
        ),
    ]
