# Generated by Django 4.0.4 on 2022-05-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_movie_car_1_movie_car_2_movie_car_3_movie_car_4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='gemres',
        ),
        migrations.AddField(
            model_name='movie',
            name='gemres',
            field=models.ManyToManyField(to='home.movie'),
        ),
    ]
