# Generated by Django 4.0.4 on 2022-05-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_genre_alter_movie_gemres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='gemres',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(help_text='enter the genre of the movie', to='home.genre'),
        ),
    ]
