# Generated by Django 4.0.4 on 2022-07-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_movie_gemres_movie_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='Languages_Spoken',
        ),
        migrations.AddField(
            model_name='movie',
            name='Languages_Spoken',
            field=models.ManyToManyField(to='home.language'),
        ),
    ]
