# Generated by Django 4.0.4 on 2022-09-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_language_remove_movie_languages_spoken_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='Languages_Spoken',
        ),
        migrations.AddField(
            model_name='movie',
            name='Languages_Spoken',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Runtime',
            field=models.DurationField(),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
