# Generated by Django 4.0.4 on 2022-09-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_movie_audience_score_alter_movie_imdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director_link',
            field=models.URLField(default=''),
        ),
    ]
