# Generated by Django 4.0.4 on 2022-09-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_movie_director_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director_link',
            field=models.URLField(),
        ),
    ]
