# Generated by Django 4.0.4 on 2022-09-24 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_movie_id_alter_movie_movie_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_name',
            new_name='name',
        ),
    ]
