# Generated by Django 4.0.4 on 2022-09-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_movie_name_movie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='id',
            field=models.CharField(default=12, max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
