# Generated by Django 4.0.4 on 2022-10-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_movie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.CharField(default=10, max_length=4),
            preserve_default=False,
        ),
    ]
