# Generated by Django 4.0.4 on 2022-10-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='cast_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='cast_3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='cast_4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='cast_5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='cast_6',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='pic_1',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='movie',
            name='pic_2',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='movie',
            name='pic_3',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='movie',
            name='pic_4',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='movie',
            name='pic_5',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='movie',
            name='pic_6',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='car_1',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='car_2',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='car_3',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='car_4',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='car_5',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
