# Generated by Django 4.0.4 on 2022-10-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_movie_cast_1_remove_movie_cast_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='cast_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='cast_3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='cast_4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='cast_5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='cast_6',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='pic_1',
            field=models.ImageField(default='images/red on black.jpg', null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='movie',
            name='pic_2',
            field=models.ImageField(default='images/red on black.jpg', null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='movie',
            name='pic_3',
            field=models.ImageField(default='images/red on black.jpg', null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='movie',
            name='pic_4',
            field=models.ImageField(default='images/red on black.jpg', null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='movie',
            name='pic_5',
            field=models.ImageField(default='images/red on black.jpg', null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='movie',
            name='pic_6',
            field=models.ImageField(default='images/red on black.jpg', null=True, upload_to='images'),
        ),
    ]
