# Generated by Django 4.0.4 on 2022-10-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_movie_cast_1_movie_cast_2_movie_cast_3_movie_cast_4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cast_1',
            field=models.CharField(default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast_2',
            field=models.CharField(default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast_3',
            field=models.CharField(default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast_4',
            field=models.CharField(default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast_5',
            field=models.CharField(default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast_6',
            field=models.CharField(default='None', max_length=50, null=True),
        ),
    ]
