# Generated by Django 4.0.4 on 2022-10-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_movie_cast_1_alter_movie_cast_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='pic_1',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
