# Generated by Django 4.0.4 on 2022-10-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_movie_pic_2_alter_movie_pic_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='pic_1',
            field=models.ImageField(default='images/red.jpg', null=True, upload_to='images'),
        ),
    ]
