# Generated by Django 4.0.4 on 2022-10-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_movie_pic_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='pic_1',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='pic_2',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='pic_3',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='pic_4',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='pic_5',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='pic_6',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
