# Generated by Django 4.0.4 on 2022-10-23 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_movie_pic_1_alter_movie_pic_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cast_1',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='cast_2',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='cast_3',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='cast_4',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='cast_5',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='cast_6',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='pic_1',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='pic_2',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='pic_3',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='pic_4',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='pic_5',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='pic_6',
        ),
    ]
