# Generated by Django 4.0.4 on 2022-10-23 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_movie_cast_1_movie_cast_2_movie_cast_3_movie_cast_4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cast_1',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='cast_2',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='cast_3',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='cast_4',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='cast_5',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='cast_6',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='pic_1',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='pic_2',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='pic_3',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='pic_4',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='pic_5',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='pic_6',
        ),
    ]
